### ISSUE TITLE
API status and Quota commands should handle `--instance` option

### ISSUE THREAD

**Issue by elacaille18** [GitGuardian/ggshield#406] opened 2022-10-26 14:39 UTC
## Is your feature request related to a problem? Please describe.

I have configured my ggshield with different GitGuardian instances:
- GitGuardian SAAS  dashboard.gitguardian.com (the default one)
- my GitGuardian on prem instance
However when trying to know the API status or the quota for both instances, it is impossible to specify which instance I want. It always gives the GG SAAS info

## Describe the solution you'd like

API status and quota commands should support the `--instance` option. Just like the `ggshield auth` and `ggshield config` command

## Describe alternatives you've considered

None. No workaround found

**Comment by agateau-gg** [comment] 2022-10-26 16:15
Looks like a duplicate of #359. Can I close it as such?

**Comment by agateau-gg** [comment] 2022-11-02 16:39
Closing as duplicate of #359.

**Closed by agateau-gg** 2022-11-02 16:39 UTC
Labels: feature request
